name: Chores

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lfscache:
    name: Keep LFS Cache Warm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create LFS file list
        id: lfs-id
        run: |
          echo "lfs-id=$(git lfs ls-files --long | cut -d ' ' -f1 | sort \
          | sha256sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: LFS Cache
        uses: actions/cache/restore@v3
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ steps.lfs-id.outputs.lfs-id }}
          restore-keys: ${{ runner.os }}-lfs-
