name: Chores

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gpac:
    name: Build GPAC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gpac/gpac

      - name: Get latest commit
        id: get-latest-commit
        run: |
          echo "latest-commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: GPAC Cache
        id: gpac-cache
        uses: actions/cache@v3
        with:
          path: /tmp/gpac
          key: ${{ runner.os }}-gpac-${{ steps.get-latest-commit.outputs.latest-commit }}

      - name: GPAC Build
        if: steps.gpac-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y build-essential pkg-config git zlib1g-dev
          ./configure --static-bin
          make -j$(nproc)
          mkdir -p /tmp/gpac
          cp -r bin/gcc/ /tmp/gpac

  lfscache:
    name: Keep LFS Cache Warm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create LFS file list
        id: lfs-id
        run: |
          echo "lfs-id=$(git lfs ls-files --long | cut -d ' ' -f1 | sort \
          | sha256sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: LFS Cache
        uses: actions/cache/restore@v3
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ steps.lfs-id.outputs.lfs-id }}
          restore-keys: ${{ runner.os }}-lfs-
