name: Build MP4Box

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gpac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gpac/gpac

      - name: Get latest commit
        id: get-latest-commit
        run: |
          echo "latest-commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: GPAC Cache
        id: gpac-cache
        uses: actions/cache@v3
        with:
          path: /tmp/gpac
          key: ${{ runner.os }}-gpac-${{ steps.get-latest-commit.outputs.latest-commit }}

      - name: GPAC Build
        if: steps.gpac-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y build-essential pkg-config git zlib1g-dev
          ./configure --static-bin
          make -j$(nproc)
          mkdir -p /tmp/gpac
          cp -r bin/gcc/ /tmp/gpac
